### ISSUE TITLE
[BUG] attributes function receive modified/formatted href

### ISSUE THREAD

**Issue by ryaa** [Hypercontext/linkifyjs#433]
The doc says that attributes option accepts a function that takes the unformatted href (https://linkify.js.org/docs/options.html#attributes) however, if there is formatHref option which has a function modifying href, the attributes function receive modified/formatted href.
The problem exists on the version 4.0.2 and 4.1.0

**Comment by nfrasser** [comment]
Hi @ryaa thanks for reporting. This should be fixed in the latest release v4.1.1

**Comment by ryaa** [comment]
I have installed and tested v4.1.1 and the above problem is still there. attributes function in options still receive formatted/modified href.
